name             'web'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures web'
long_description 'Installs/Configures web'
version          '0.1.0'
